export default interface Song {
    id: string
    type: string
    song: string
    album: string
    year: string
    music: string
    music_id: string
    primary_artists: string
    primary_artists_id: string
    featured_artists: string
    featured_artists_id: string
    singers: string
    starring: string
    image: string
    label: string
    albumid: string
    language: string
    origin: string
    play_count: number
    is_drm: number
    copyright_text: string
    is_dolby_content: boolean
    explicit_content: number
    has_lyrics: string
    lyrics_snippet: string
    encrypted_drm_media_url: string
    encrypted_media_url: string
    encrypted_media_path: string
    media_preview_url: string
    download_url: string
    perma_url: string
    album_url: string
    duration: string
    webp: boolean
    cache_state: string
    starred: string
    artistMap: any[]
    release_date: string
    vcode: string
    vlink: string
    triller_available: boolean
    label_url: string
    weight: number
    rights: any[]
    secondary_subtitle: string
}
